apiVersion: v1
kind: Pod
metadata:
  name: fail-4-dns-failure-pod
  labels:
    tier: triage-gauntlet
    scenario: dns-failure
spec:
  containers:
    - name: client
      image: curlimages/curl:8.6.0
      command: ["sh", "-c"]
      args:
        - |
          echo "Attempting connection to internal database...";
          # BUG: Incorrect internal hostname
          curl -s --connect-timeout 3 http://postgres-db-wrong-name.production.svc.cluster.local:5432 || true
          echo "Process sleeping...";
          sleep 3600
