apiVersion: v1
kind: Pod
metadata:
  name: fail-1-crashloop-pod
  labels:
    tier: triage-gauntlet
    scenario: crashloop
spec:
  containers:
    - name: python-app
      image: python:3.11-alpine
      command:
        - "python3"
        - "-c"
        - |
          import os, sys
          db_url = os.environ.get("DATABASE_URL")
          if not db_url:
              print("[FATAL ERROR]: DATABASE_URL environment variable is MISSING!", file=sys.stderr)
              sys.exit(1)
          print("Application started successfully!")
