apiVersion: v1
kind: Pod
metadata:
  name: fail-2-imagepull-pod
  labels:
    tier: triage-gauntlet
    scenario: imagepull
spec:
  containers:
    - name: web-app
      # BUG: Typo in image name and tag
      image: yatri-api-service:v999-invalid-tag-does-not-exist
