apiVersion: v1
kind: Pod
metadata:
  name: fail-3-pending-pod
  labels:
    tier: triage-gauntlet
    scenario: pending
spec:
  containers:
    - name: hungry-app
      image: nginx:alpine
      resources:
        requests:
          # BUG: Demanding 500 CPU cores ensures the pod can never be scheduled!
          cpu: "500"
          memory: "1000Gi"
